In [49]:
import numpy as np
import scipy.special
class neuralNetwork:

    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
    
        self.inodes = inputnodes #입력 레이어의 노드 수 설정
        self.hnodes = hiddennodes #히든 레이어의 노드 수 설정
        self.onodes = outputnodes #출력 레이어의 노드 수 설정

        self.lr = learningrate #학습률 설정
        self.wih = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        self.who = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))
        
        self.activation_function = lambda x: scipy.special.expit(x)

        pass

    def train(self, inputs_list, targets_list): #신경망 훈련
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T

        hidden_inputs = np.dot(self.wih, inputs)

        hidden_outputs = self.activation_function(hidden_inputs)

        final_inputs = np.dot(self.who, hidden_outputs)

        final_outputs = self.activation_function(final_inputs)

        output_errors = targets - final_outputs

        hidden_errors = np.dot(self.who.T, output_errors)

        self.who += self.lr * np.dot((output_errors * final_outputs * (1.0-final_outputs)), np.transpose(hidden_outputs)) #학습률과 오차를 반영하여 가중치를 수정하는 공식을 코드로 구현

        self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), np.transpose(inputs))



        pass

    def query(self, inputs_list): #신경망에 질문

        inputs = np.array(inputs_list, ndmin=2).T

        hidden_inputs = np.dot(self.wih, inputs)

        hidden_outputs = self.activation_function(hidden_inputs)

        final_inputs = np.dot(self.who, hidden_outputs)

        final_outputs = self.activation_function(final_inputs)

        return final_outputs

input_nodes = 3
hidden_nodes = 3
output_nodes = 3

learning_rate = 0.001

#신경망 객체 만들기
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

In [51]:
input = [0.7, 0.4, 0.2]
target = [0.8, 0.1, 0.9]
epochs = 10000000

for i in range(epochs+1):
  n.train(input, target)
  if i % 1000000 == 0:
    total_error = (target - n.query(input)) **2
    print('epochs:{}'.format(i))
    print('total error:{}'.format(total_error))
    print('current value:{}'.format(n.query(input)))

epochs:0
total error:[[1.41620818e-19 4.89999999e-01 1.00000001e-02]
 [4.90000017e-01 1.40836767e-16 6.40000019e-01]
 [9.99999744e-03 6.39999980e-01 1.63907402e-16]]
current value:[[0.8       ]
 [0.09999999]
 [0.89999999]]
epochs:1000000
total error:[[4.04703394e-26 4.90000000e-01 1.00000000e-02]
 [4.90000000e-01 2.58977662e-25 6.40000000e-01]
 [1.00000000e-02 6.40000000e-01 5.11677974e-25]]
current value:[[0.8]
 [0.1]
 [0.9]]
epochs:2000000
total error:[[3.75328309e-26 4.90000000e-01 1.00000000e-02]
 [4.90000000e-01 2.28065878e-25 6.40000000e-01]
 [1.00000000e-02 6.40000000e-01 5.07556669e-25]]
current value:[[0.8]
 [0.1]
 [0.9]]
epochs:3000000
total error:[[3.51625011e-26 4.90000000e-01 1.00000000e-02]
 [4.90000000e-01 2.28065878e-25 6.40000000e-01]
 [1.00000000e-02 6.40000000e-01 5.04240088e-25]]
current value:[[0.8]
 [0.1]
 [0.9]]
epochs:4000000
total error:[[3.31923210e-26 4.90000000e-01 1.00000000e-02]
 [4.90000000e-01 2.28065878e-25 6.40000000e-01]
 [1.00000000e-02 6.40000000e-0